### PR TITLE
Shokoufeh amirsoleymani

### PR DESCRIPTION
**Pull request by yalda-amirsoleymani**

### CODE REVIEW

**Comment by zucchett** [comment]
Please remove all unnecessary files (especially data files and images) so a can proceed with the merge.

**Comment by yalda-amirsoleymani** [comment]
> Please remove all unnecessary files (especially data files and images) so a can proceed with the merge.

Hello. Actually TA told me that I should add the figures and outputs. On the other hand if I remove data files there would be error in running the code. So how you can test it. What can I do know?

**Comment by zucchett** [comment]
That's the reason why i need the output text and images, but NOT the input files and input images (i said this in class multiple times).
If i have the output, i don't need to re-run the code, i will inspect the output and the source.

**Comment by yalda-amirsoleymani** [comment]
> That's the reason why i need the output text and images, but NOT the input files and input images (i said this in class multiple times). If i have the output, i don't need to re-run the code, i will inspect the output and the source.

Hello. I deleted input files from data folder, and just added outputs and figures. I had different python files for each question, so tried not to miss any output. Please take a look at the code if you couldn't find something that you expected to see. Or let me know to fix the problem.  Next time I'll write the code in jupyter  file to be more convenient for you. Thank you

**Comment by zucchett** [comment]
I can see that data files in individual directories are still included, e.g. 05ex_pandas/data_000637.txt and others.

**Comment by yalda-amirsoleymani** [comment]
> I can see that data files in individual directories are still included, e.g. 05ex_pandas/data_000637.txt and others.

Hello professor, I deleted other files as well.

**Pull request merged**
