### PR TITLE
Yazzedhusseinyounis abdalla

### PR DESCRIPTION
**Pull request by abdallayaz**

### CODE REVIEW

**Comment by zucchett** [comment]
Please remove all unnecessary files (especially data files, jupyter checkoints and images) so a can proceed with the merge.

**Comment by abdallayaz** [comment]
> Please remove all unnecessary files (especially data files, jupyter checkoints and images) so a can proceed with the merge.

how i can remove it exactly ?

**Comment by zucchett** [comment]
The data files are still included, please remove them.

**Comment by abdallayaz** [comment]
i deleted

**Comment by zucchett** [comment]
You are deleting all previous exercises, which you don't really want to do; you need to add them back!

**Pull request merged**
