### PR TITLE
Exercise 4,5,6,7

### PR DESCRIPTION
**Pull request by aysekilicunipd**

### CODE REVIEW

**Comment by zucchett** [comment]
Please remove all unnecessary files (especially data files and images) so a can proceed with the merge.

**Comment by aysekilicunipd** [comment]
I removed the unnecessary files. Thank you so much for your time.

Kind regards.

**Comment by zucchett** [comment]
I see that the .xtx, .csv, .json , .dat files are still there, please remove them.

**Comment by aysekilicunipd** [comment]
Everything is fine now. Sorry for my misunderstanding in the first place.

**Pull request merged**
