### PR TITLE
Exercises 04, 05, 06, 07

### PR DESCRIPTION
**Pull request by AldaKola**

### CODE REVIEW

**Comment by zucchett** [comment]
1) solve the conflicts, otherwise i won't be able to merge
2) do not modify the exercises of the first block

**Comment by AldaKola** [comment]
I solved all the conflicts, I   hope there isn't any more issues.

**Comment by zucchett** [comment]
You still need to address point 2:

2. do not modify the exercises of the first block

**Review by AldaKola — COMMENTED** [review]
Removed conflict files

**Comment by zucchett** [comment]
Unless you want to lose the 01ex_introduction.py file, you need to add it back.

**Pull request merged**
