### PR TITLE
New Pull request

### PR DESCRIPTION
**Pull request by mustapha-colley**

### CODE REVIEW

**Comment by zucchett** [comment]
Please remove all unnecessary files (especially data files and images) so a can proceed with the merge.

**Comment by mustapha-colley** [comment]
I have deleted all the files you deemed unnecessary.
Apologies for the inconvenience.

**Comment by zucchett** [comment]
The data files are still there in the data/ directory, please remove them.

**Comment by mustapha-colley** [comment]
all files in the data/ directory have been deleted.

**Pull request merged**
