### PR TITLE
Huan chen

### PR DESCRIPTION
**Pull request by HuanChen2022**
Exercise 04--07 virsion1

### CODE REVIEW

**Comment by zucchett** [comment]
1) solve the conflicts, otherwise i won't be able to merge
2) Please remove all unnecessary files (especially data files and images from the lectures). Leave only the files of the exercises
3) do not modify the exercises of the first block.

**Comment by RoccoA97** [comment]
Hi @HuanChen2022,

I had another look at the PR and at your fork history.
Did you cancel your fork after the first block deadline and then forked again? Looks like after the first deadline, you did so and in the new fork there were not the solutions from ex 01-02-03, so you added them back in one of the commits.
That would explain the mess.

By the way, can you solve the conflicts in `01ex_introduction.ipynb` and `03ex_numberRepresentation/03ex_numberRepresentation_es02.py`? Then, we will proceed with the merge since it's the easiest way to solve. I will give another look to check if the exercises are the same with respect to the first Pull Request, but it looks so

**Comment by HuanChen2022** [comment]
I delete the 01ex_introduction.ipynb, and I only added some comments on the question in the
03ex_numberRepresentation/03ex_numberRepresentation_es02.py and it influence nothing about the solution of that exercise
| |
陈焕
|
|
***@***.***
|


---- Replied Message ----
| From | Rocco ***@***.***> |
| Date | 12/14/2022 13:04 |
| To | ***@***.***> |
| Cc | Huan ***@***.***> ,
***@***.***> |
| Subject | Re: [zucchett/ScientificComputingWithPython2022] Huan chen (PR #310) |

Hi @HuanChen2022,

I had another look at the PR and at your fork history.
Did you cancel your fork after the first block deadline and then forked again? Looks like after the first deadline, you did so and in the new fork there were not the solutions from ex 01-02-03, so you added them back in one of the commits.
That would explain the mess.

By the way, can you solve the conflicts in 01ex_introduction.ipynb and 03ex_numberRepresentation/03ex_numberRepresentation_es02.py? Then, we will proceed with the merge since it's the easiest way to solve. I will give another look to check if the exercises are the same with respect to the first Pull Request, but it looks so

**Comment by zucchett** [comment]
As @RoccoA97 commented, you need to solve the conflicts first, otherwise it's impossible to merge the PR.

**Comment by RoccoA97** [comment]
@HuanChen2022 ok, now just delete the images and we can merge

**Pull request merged**
