### PR TITLE
Katourian

### PR DESCRIPTION
**Pull request by mvanaee**
Last Exercises Block

### CODE REVIEW

**Comment by zucchett** [comment]
Please remove the 07ex exercises; it's not allowed to modify the previous exercises!

**Comment by mvanaee** [comment]
I checket it and It is not my commit. I think it is your commit.
I have not modified anything from previous exercises. 
Am I wrong?

**Comment by mvanaee** [comment]
Only last commits are mine professor. That commit is "zucchett committed on Nov 24, 2022"

**Comment by zucchett** [comment]
It's simply not possible that i made a commit to _your_ repository!
It says like this because i was the creator of the original file. Since 07 ex belongs to the previous set of exercises, please drop it form this PR.

**Comment by mvanaee** [comment]
I have removed 07ex file. It that ok now?

I think I got what the problem is. One of my previous PRs was from my "main" branch, but others were from "katourian" and these two were not merged. And this caused this problem.
I have not modified 07ex file. Actually I uploade my files in a seperate folder, not in the main file. So that file was just the questions, not answers.

**Comment by zucchett** [comment]
Thanks, it is fine now.

**Pull request merged**
