### PR TITLE
Second Block of Homeworks #4-5-6-7

### PR DESCRIPTION
**Pull request by cerenyilmazgulten**

### CODE REVIEW

**Comment by zucchett** [comment]
As i said multiple times in class: except the first block (01ex, 02ex, 03ex), for all the other exercises you need to add the text output and the output plots, OR (better) use the jupyter notebooks and running all the cells. Please update the pull request with what is missing.

**Comment by cerenyilmazgulten** [comment]
Files were updated to jupyter notebook

**Review by cerenyilmazgulten — COMMENTED** [review]
Updated Block 2 HW

**Comment by zucchett** [comment]
Thanks, now it's perfect.

**Pull request merged**
