### PR TITLE
Batch exercise2

### PR DESCRIPTION
**Pull request by hamid-rostami**
My solutions for exercises 4 to 7.
I put all data under `data` directory, including various datasets, script's output and figures.

### CODE REVIEW

**Comment by zucchett** [comment]
Please remove all unnecessary files (especially data files and images) so a can proceed with the merge.

**Comment by zucchett** [comment]
He was referring only to the plots that you produce. The images included in the lecture notebooks are not needed and they can be removed.

Yes, it's ok and necessary to remove the data, but you need to run the cells in the notebooks OR add the txt output so we can check that the exercises are correct.

**Comment by hamid-rostami** [comment]
I've removed some files from `data` directory. However, still there are text output of exercises and figures generated by `matplotlib`.
Please let me know if there were some other issues.

**Comment by hamid-rostami** [comment]
Incidentally, the `images` directory is in my branch, because I keep my branch up-to-date with `upstream/main`. If it's not necessary, please tell me to stop doing it.

**Comment by zucchett** [comment]
Ok, i see now that you have solved the exercises in the .py and that the .ipynb are actually empty. Forget my previous message.

**Pull request merged**
